package model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.18 at 04:52:49 PM IST 
//



import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the progs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: progs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Entity.Attribute }
     * 
     */
    public Entity.Attribute createEntityAttribute() {
        return new Entity.Attribute();
    }

    /**
     * Create an instance of {@link Entity.Attribute.Properties }
     * 
     */
    public Entity.Attribute.Properties createEntityAttributeProperties() {
        return new Entity.Attribute.Properties();
    }

    /**
     * Create an instance of {@link Entity.Attribute.Properties.SchemaBasedProperties }
     * 
     */
    public Entity.Attribute.Properties.SchemaBasedProperties createEntityAttributePropertiesSchemaBasedProperties() {
        return new Entity.Attribute.Properties.SchemaBasedProperties();
    }

    /**
     * Create an instance of {@link Entity.Attribute.DesignTime }
     * 
     */
    public Entity.Attribute.DesignTime createEntityAttributeDesignTime() {
        return new Entity.Attribute.DesignTime();
    }

    /**
     * Create an instance of {@link Entity.Attribute.Properties.SchemaBasedProperties.LABEL }
     * 
     */
    public Entity.Attribute.Properties.SchemaBasedProperties.LABEL createEntityAttributePropertiesSchemaBasedPropertiesLABEL() {
        return new Entity.Attribute.Properties.SchemaBasedProperties.LABEL();
    }

    /**
     * Create an instance of {@link Entity.Attribute.DesignTime.Attr }
     * 
     */
    public Entity.Attribute.DesignTime.Attr createEntityAttributeDesignTimeAttr() {
        return new Entity.Attribute.DesignTime.Attr();
    }

}
